### ISSUE TITLE
[rush] pnpm 3.5.3 + rush 5.9.1 `rush update` fails to link

### ISSUE THREAD

**Issue by calebmshafer** [microsoft/web-build-tools#1347]
During the move to pnpm 3.5.3 and rush 5.9.1, I deleted the shrinkwrap file and ran a `rush update --full --purge`.  It successfully makes it through the pnpm install step but fails during the linking phase and receive this error,

```
ERROR: Internal Error: Cannot find installed dependency "@microsoft/api-extractor" in "C:\dev\imodeljs\imodeljs\common\temp\node_modules\.local\C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fbuild-tools.tgz\node_modules"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

The actual file path that exists in the .local folder for the package is, `"C:\dev\imodeljs\imodeljs\common\temp\node_modules\.local\C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fbuild-tools.tgz_2a665c89609864b4e75bc5365d7f8f56"`.

It looks like this may be related to how pnpm resolves peer dependencies, https://pnpm.js.org/docs/en/how-peers-are-resolved.html, but that's just a guess based on some of the other paths in the `.local` folder,

```
"C:\dev\imodeljs\imodeljs\common\temp\node_modules\.local\C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fpresentation-frontend.tgz_jsdom@11.12.0"
"C:\dev\imodeljs\imodeljs\common\temp\node_modules\.local\C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fpresentation-integration-tests.tgz_jsdom@11.12.0"
```

If you'd like to reproduce the issue, the [iModel.js](https://github.com/imodeljs/imodeljs) repo when updated to use the new rush and pnpm versions will work.  I can always make a separate repro repo if needed with the updated versions.

**Comment by sachinjoseph** [comment]
Thanks @calebmshafer. It will help if you can provide repro repo and repro steps with the latest version of Rush.

**Comment by sachinjoseph** [comment]
pnpm 3.5.3 is known to be incompatible with Rush version <= 5.9.1.

**Comment by calebmshafer** [comment]
Just setup the repro repo here, https://github.com/calebmshafer/imodeljs_rush_bug_repro.

The steps are,
1. Delete `common\config\rush\shrinkwrap.yaml`
1. Run `node common\scripts\install-run-rush.js update`

Then you should see the error pasted above.

**Comment by calebmshafer** [comment]
FWIW, I can reproduce this with Rush 5.10.0 as well. 

I have been following #1142, as we've been experiencing the same issue, and with the fix pushed I attempted to update to the latest pnpm and Rush.  That's when I discovered this problem.

**Comment by sachinjoseph** [comment]
I can repro this on Rush 5.10.0 and pnpm 3.5.3. Looking into this.

**Comment by kelseyyoung** [comment]
I think I've seen this; I believe it's because you're missing peer dependencies in your package.json required by a different package you depend on

So for example in your second text block you probably need to depend on jsdom because another package you require has a peer dependency on it

**Comment by agrittmsft** [comment]
Seems to not be an issue if you use Rush 5.10.0 and pnpm 2.25.6.

**Comment by cortopy** [comment]
Same error here with a different package. I've tried patching the dependency by moving the peer dependency into a proper dependency, but issue persists.
Using pnpm 2.25.6 also works for me

**Comment by calebmshafer** [comment]
It works on in pnpm 2.25.7 as well, that's the version we're currently stuck on.  I haven't tracked down all of the peer dependencies and promoted them to real dependencies but I can see if that works.

**Comment by sachinjoseph** [comment]
https://github.com/microsoft/web-build-tools/pull/1367

**Comment by apostolisms** [comment]
@calebmshafer this should be fixed now in version [5.10.1](https://github.com/microsoft/web-build-tools/blob/master/apps/rush/CHANGELOG.md)

**Comment by calebmshafer** [comment]
I can confirm it fixes the issue with installing.  Thanks!

Hitting a slightly different issue now but I will open a new bug for it.

**Comment by alex-shamshurin** [comment]
The same is with latest rush 5.15.1 and pnpm 4.0.2

**Comment by maneetgoyal** [comment]
This issue seems to be back in pnpm 6.0.2

**Comment by robertkibet** [comment]
> This issue seems to be back in pnpm 6.0.2

@maneetgoyal I would suggest you change to pnpm version 5.7.0 which worked for me. I was on the same version as yours `v6.0.2` and encountered a similar linking problem, but it worked with `v5.7.0` finally. :+1:

**Comment by maneetgoyal** [comment]
Thanks @robertkibet, it worked with pnpm v5.18.9 too

**Comment by ApolloTang** [comment]
in https://github.com/microsoft/rushstack/issues/2764, it said it is recently fixed by v5.47.0
